### ISSUE TITLE
RSeQC module not properly installing all dependencies

### ISSUE THREAD

**Issue by Nick-Eagles** [LieberInstitute/jhpce_mod_source#1]
Details:
When running the python script https://github.com/LieberInstitute/RNAsp/blob/master/scripts/infer_experiment.py as part of the RNAsp pipeline (which internally uses "module load RSeQC"), I get the error: "ImportError: No module named bx.bitset". The "bx" package is a dependency of RSeQC and the issue was resolved after "pip install --user RSeQC" (locally getting a fresh install of the module).

**Comment by lcolladotor** [comment]
@Nick-Eagles is this still an open issue? or has it been resolved?

**Comment by Nick-Eagles** [comment]
Ah it looks like Brianna fixed this in https://github.com/LieberInstitute/jhpce_mod_source/commit/87d4952
